### ISSUE TITLE
Monitor Jekyll release and update to 4 when it's available.

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma-website#7]
We get the folliowing warning when setting up jekyll for the website:

```
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
```

According to this we should upgrade to sassc.

**Comment by slavfox** [comment]
Looks like Jekyll has a runtime dependency on [jekyll-sass-converter](https://github.com/jekyll/jekyll-sass-converter/), where the [master has already updated to sassc](https://github.com/jekyll/jekyll-sass-converter/blob/master/History.markdown), but Jekyll itself will update its dependencies with the next major release (https://github.com/fieldtrip/website/issues/104#issuecomment-483993361, https://github.com/jekyll/jekyll-sass-converter/issues/74#issuecomment-483991957).

Quoting:
>the thing to do here is just ignore the message and wait until Jekyll 4.0 comes out.

**Comment by PaulBone** [comment]
I'm glad I asked and didn't try to solve it myself!  But now we get to look forward to a major version update..

Thanks @slavfox 

I'm going to leave the bug open to remind myself to update to 4.0.

**Comment by PaulBone** [comment]
This is done.
